name: tension_ceiling_app
description: Приложение для смет натяжных потолков
version: 1.0.9+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  path_provider: ^2.1.0
  provider: ^6.0.5
  intl: ^0.18.1
  share_plus: ^12.0.1
  file_picker: ^10.3.8
  printing: ^5.14.2
  open_filex: ^4.7.0
  permission_handler: ^11.3.0    # Измените с ^12.0.1 на ^11.3.0
  excel: ^4.0.6
  pdf: ^3.11.3
  flutter_svg: ^2.0.10+1        # Уже изменено ранее
  syncfusion_flutter_datagrid: ^22.2.12
  syncfusion_flutter_pdf: ^22.2.12
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
